using Model;
using Model.Bidding;
using Model.Bidding.AI;
using Model.Bidding.AI.Engine;
using Model.Enums;
using Trumpfish.Server.Contracts;

namespace Trumpfish.Server.Services;

/// <summary>
/// Runs the shared <see cref="BidEngine"/> over deals generated by the web client. Nothing is persisted - the whole batch is simulated in memory
/// and mapped to the transport contracts so the client can render hands, points and the full auction.
/// </summary>
public class BiddingSimulator : IBiddingSimulator {

    /// <summary>Hard stop for pathological auctions, so a broken system tree cannot hang a request.</summary>
    private const int MaxBids = 60;


    public SimulationResponse Simulate(BiddingSystem system, SimulationRequest request) {
        var results = new List<SimulationDealResult>(request.Deals.Count);

        for (var i = 0; i < request.Deals.Count; i++) {
            results.Add(SimulateDeal(system, request.Deals[i], i));
        }

        return new SimulationResponse(system.SystemName, results.Count, results.Count(e => e.Error != null), results, request.Seed);
    }


    private static SimulationDealResult SimulateDeal(BiddingSystem system, SimulationDealRequest deal, int index) {
        if (deal.Hands.Count != 4 || deal.Hands.Any(hand => hand.Cards.Count != 13) || deal.Hands.Select(e => e.Position).Distinct().Count() != 4) {
            return new SimulationDealResult(index, deal.Dealer, [], [], AuctionMapping.PassedOut(), "Every deal must contain four distinct hands of thirteen cards.");
        }

        var hands = BuildHands(deal);
        var auction = new Auction();
        var players = new Player[4];

        foreach (var position in Enum.GetValues<PlayerPosition>()) {
            players[(int)position] = new Player("bot", position, new BidEngine(auction, position, system));
            players[(int)position].GiveHand(hands[position]);
        }

        auction.Start(deal.Dealer);

        string? error = null;
        try {
            while (!auction.IsCompleted()) {
                if (auction.AuctionHistory.Count >= MaxBids) {
                    error = "Auction did not finish within the allowed number of bids.";
                    break;
                }

                auction.Submit(players[(int)auction.CurrentBidder].MakeBid(index));
            }
        }
        catch (Exception exception) {
            error = exception.Message;
        }

        var bidding = AuctionMapping.MapBidding(auction);
        var contract = AuctionMapping.PassedOut();

        if (error == null) {
            try {
                contract = AuctionMapping.MapContract(auction, players, hands);
            }
            catch (Exception exception) {
                error = exception.Message;
            }
        }

        return new SimulationDealResult(index, deal.Dealer, AuctionMapping.MapHands(hands), bidding, contract, error);
    }


    private static Dictionary<PlayerPosition, Hand> BuildHands(SimulationDealRequest deal) {
        return deal.Hands.ToDictionary(e => e.Position, e => new Hand(e.Cards.Select(card => new Card(card.Value, card.Color))));
    }
}
