using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Trumpfish.Server.Contracts;
using Trumpfish.Server.Services;

namespace Trumpfish.Server.Controllers;

/// <summary>
/// Runs the AI bidding engine over deals generated by the web client. Deals are never stored - the client owns generation, the server owns simulation.
/// </summary>
[ApiController]
[Authorize]
[Route("api/simulation")]
[Produces("application/json")]
public class SimulationController : ControllerBase {

    private const int MaxDeals = 500;

    private readonly IBiddingSystemStore _store;
    private readonly IBiddingSimulator _simulator;


    public SimulationController(IBiddingSystemStore store, IBiddingSimulator simulator) {
        _store = store;
        _simulator = simulator;
    }


    [HttpPost("bidding")]
    [ProducesResponseType<SimulationResponse>(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<SimulationResponse>> SimulateBidding([FromBody] SimulationRequest request, CancellationToken cancellationToken) {
        if (request.SystemId == Guid.Empty) {
            return BadRequest("System id is required.");
        }

        if (request.Deals.Count == 0) {
            return BadRequest("At least one deal is required.");
        }

        if (request.Deals.Count > MaxDeals) {
            return BadRequest($"At most {MaxDeals} deals can be simulated in a single request.");
        }

        var operation = await _store.GetAsync(request.SystemId, User.RequireUserId(), User.IsAdmin(), cancellationToken);
        if (operation.Result != SystemAccessResult.Success) {
            return NotFound("Nie znaleziono systemu licytacyjnego.");
        }

        return Ok(_simulator.Simulate(operation.Value!, request));
    }
}
