using Microsoft.AspNetCore.Mvc;
using Trumpfish.Server.Contracts;
using Trumpfish.Server.Services;

namespace Trumpfish.Server.Controllers;

/// <summary>
/// Runs the AI bidding engine over deals generated by the web client. Deals are never stored - the client owns generation, the server owns simulation.
/// </summary>
[ApiController]
[Route("api/simulation")]
[Produces("application/json")]
public class SimulationController : ControllerBase {

    private const int MaxDeals = 500;

    private readonly IBiddingSystemStore _store;
    private readonly IBiddingSimulator _simulator;


    public SimulationController(IBiddingSystemStore store, IBiddingSimulator simulator) {
        _store = store;
        _simulator = simulator;
    }


    [HttpPost("bidding")]
    [ProducesResponseType<SimulationResponse>(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<SimulationResponse>> SimulateBidding([FromBody] SimulationRequest request, CancellationToken cancellationToken) {
        if (string.IsNullOrWhiteSpace(request.SystemName)) {
            return BadRequest("System name is required.");
        }

        if (request.Deals.Count == 0) {
            return BadRequest("At least one deal is required.");
        }

        if (request.Deals.Count > MaxDeals) {
            return BadRequest($"At most {MaxDeals} deals can be simulated in a single request.");
        }

        var system = await _store.GetAsync(request.SystemName, cancellationToken);
        if (system == null) {
            return NotFound($"Bidding system '{request.SystemName}' was not found.");
        }

        return Ok(_simulator.Simulate(system, request));
    }
}
