// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trumpfish.Server.Data;

#nullable disable

namespace Trumpfish.Server.Data.Migrations
{
    [DbContext(typeof(TrumpfishDbContext))]
    [Migration("20260917164750_AddSlamConventionIndexToBidNodes")]
    partial class AddSlamConventionIndexToBidNodes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trumpfish.Server.Data.BidNodeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Aces")
                        .HasColumnType("integer");

                    b.Property<string>("AiSource")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<bool>("Alert")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutomaticResponse")
                        .HasColumnType("boolean");

                    b.Property<int?>("ClubsLower")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ClubsStops")
                        .HasColumnType("numeric");

                    b.Property<int?>("ClubsUpper")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ColorDistribution")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<Guid?>("ContinuationNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Convention")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("DiamondsLower")
                        .HasColumnType("integer");

                    b.Property<decimal?>("DiamondsStops")
                        .HasColumnType("numeric");

                    b.Property<int?>("DiamondsUpper")
                        .HasColumnType("integer");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<string>("FiguresJson")
                        .HasColumnType("text");

                    b.Property<bool>("GameForcing")
                        .HasColumnType("boolean");

                    b.Property<bool>("GoToOpenings")
                        .HasColumnType("boolean");

                    b.Property<int?>("HeartsLower")
                        .HasColumnType("integer");

                    b.Property<decimal?>("HeartsStops")
                        .HasColumnType("numeric");

                    b.Property<int?>("HeartsUpper")
                        .HasColumnType("integer");

                    b.Property<int?>("InputBidColor")
                        .HasColumnType("integer");

                    b.Property<string>("InterjectionColor")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("InterjectionExplanation")
                        .HasColumnType("text");

                    b.Property<bool?>("InterjectionIsFromSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("InterjectionType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("InterjectionValue")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFromSystem")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("boolean");

                    b.Property<int?>("Kings")
                        .HasColumnType("integer");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("OneRoundForcing")
                        .HasColumnType("boolean");

                    b.Property<bool>("OpenerBid")
                        .HasColumnType("boolean");

                    b.Property<int?>("OutputGameColor")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PointsLower")
                        .HasColumnType("integer");

                    b.Property<int?>("PointsUpper")
                        .HasColumnType("integer");

                    b.Property<string>("RealizedGoal")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("RootId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SignOff")
                        .HasColumnType("boolean");

                    b.Property<int?>("SlamConventionIndex")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("SpadesLower")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SpadesStops")
                        .HasColumnType("numeric");

                    b.Property<int?>("SpadesUpper")
                        .HasColumnType("integer");

                    b.Property<bool>("TryPremiumContract")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("RootId");

                    b.HasIndex("RootId", "NodeId")
                        .IsUnique();

                    b.ToTable("BidNodes");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.BiddingRootRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BiddingSystemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BiddingSystemId");

                    b.ToTable("BiddingRoots");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.BiddingSystemRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ForkedFromId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ForkedFromVersionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ForkedFromId");

                    b.HasIndex("IsSeed");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("OwnerId", "Name"), false);

                    b.ToTable("BiddingSystems");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.FriendshipRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcceptedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId", "AddresseeId")
                        .IsUnique();

                    b.ToTable("Friendships");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.SavedDealRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Deal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dealer")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Declarer")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SavedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Vulnerability")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "SavedUtc");

                    b.HasIndex("OwnerId", "Level", "Color");

                    b.ToTable("SavedDeals");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.SavedDealShareRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SharedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DealId", "ToUserId")
                        .IsUnique();

                    b.HasIndex("ToUserId", "SharedUtc");

                    b.ToTable("SavedDealShares");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.UserRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.BidNodeRecord", b =>
                {
                    b.HasOne("Trumpfish.Server.Data.BidNodeRecord", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Trumpfish.Server.Data.BiddingRootRecord", "Root")
                        .WithMany("Bids")
                        .HasForeignKey("RootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Root");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.BiddingRootRecord", b =>
                {
                    b.HasOne("Trumpfish.Server.Data.BiddingSystemRecord", "BiddingSystem")
                        .WithMany("Roots")
                        .HasForeignKey("BiddingSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BiddingSystem");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.BiddingSystemRecord", b =>
                {
                    b.HasOne("Trumpfish.Server.Data.BiddingSystemRecord", "ForkedFrom")
                        .WithMany("Forks")
                        .HasForeignKey("ForkedFromId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Trumpfish.Server.Data.UserRecord", "Owner")
                        .WithMany("BiddingSystems")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ForkedFrom");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.FriendshipRecord", b =>
                {
                    b.HasOne("Trumpfish.Server.Data.UserRecord", "Addressee")
                        .WithMany()
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Trumpfish.Server.Data.UserRecord", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.SavedDealRecord", b =>
                {
                    b.HasOne("Trumpfish.Server.Data.UserRecord", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.SavedDealShareRecord", b =>
                {
                    b.HasOne("Trumpfish.Server.Data.SavedDealRecord", "Deal")
                        .WithMany("Shares")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trumpfish.Server.Data.UserRecord", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Deal");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.BidNodeRecord", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.BiddingRootRecord", b =>
                {
                    b.Navigation("Bids");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.BiddingSystemRecord", b =>
                {
                    b.Navigation("Forks");

                    b.Navigation("Roots");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.SavedDealRecord", b =>
                {
                    b.Navigation("Shares");
                });

            modelBuilder.Entity("Trumpfish.Server.Data.UserRecord", b =>
                {
                    b.Navigation("BiddingSystems");
                });
#pragma warning restore 612, 618
        }
    }
}
