/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentUser"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentUser"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentUser"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                    "text/json": components["schemas"]["ChangePasswordRequest"];
                    "application/*+json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProfileRequest"];
                    "text/json": components["schemas"]["UpdateProfileRequest"];
                    "application/*+json": components["schemas"]["UpdateProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CurrentUser"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bidding-systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BiddingSystemSummary"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaveSystemRequest"];
                    "text/json": components["schemas"]["SaveSystemRequest"];
                    "application/*+json": components["schemas"]["SaveSystemRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BiddingSystemSummary"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bidding-systems/seeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BiddingSystemSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bidding-systems/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BiddingSystem"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BiddingSystem"];
                    "text/json": components["schemas"]["BiddingSystem"];
                    "application/*+json": components["schemas"]["BiddingSystem"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BiddingSystemSummary"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bidding-systems/{id}/name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RenameSystemRequest"];
                    "text/json": components["schemas"]["RenameSystemRequest"];
                    "application/*+json": components["schemas"]["RenameSystemRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BiddingSystemSummary"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bidding-systems/{id}/fork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BiddingSystemSummary"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bidding-systems/{id}/refork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BiddingSystemSummary"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bidding-systems/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BiddingSystem"];
                    "text/json": components["schemas"]["BiddingSystem"];
                    "application/*+json": components["schemas"]["BiddingSystem"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationIssue"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice/deal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PracticeStartRequest"];
                    "text/json": components["schemas"]["PracticeStartRequest"];
                    "application/*+json": components["schemas"]["PracticeStartRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PracticeState"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice/bid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PracticeBidRequest"];
                    "text/json": components["schemas"]["PracticeBidRequest"];
                    "application/*+json": components["schemas"]["PracticeBidRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PracticeState"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/practice/hint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PracticeHintRequest"];
                    "text/json": components["schemas"]["PracticeHintRequest"];
                    "application/*+json": components["schemas"]["PracticeHintRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PracticeHint"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/simulation/bidding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SimulationRequest"];
                    "text/json": components["schemas"]["SimulationRequest"];
                    "application/*+json": components["schemas"]["SimulationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimulationResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Bid: {
            type?: components["schemas"]["BidType"];
            color?: components["schemas"]["BidColor"];
            /** Format: int32 */
            value?: null | number | string;
            isFromSystem?: boolean;
            explanation?: null | string;
        };
        /** @enum {unknown} */
        BidColor: "NoColor" | "Clubs" | "Diamonds" | "Hearts" | "Spades" | "NoTrump";
        BiddingGoal: number;
        BiddingSystem: {
            systemName?: string;
            roots?: components["schemas"]["Root"][];
        };
        BiddingSystemSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: int32 */
            rootCount: number | string;
            /** Format: int32 */
            bidCount: number | string;
            /** Format: date-time */
            modifiedUtc: string;
            isSeed: boolean;
            /** Format: uuid */
            forkedFromId: null | string;
            forkedFromName: null | string;
            seedUpdateAvailable: boolean;
        };
        BidNode: {
            /** Format: uuid */
            nodeId?: string;
            description?: null | string;
            condition?: null | string;
            convention?: null | string;
            pointsRange?: null | components["schemas"]["NumberRange"];
            spadesCardRange?: null | components["schemas"]["NumberRange"];
            heartsCardRange?: null | components["schemas"]["NumberRange"];
            diamondsCardRange?: null | components["schemas"]["NumberRange"];
            clubsCardRange?: null | components["schemas"]["NumberRange"];
            /** Format: double */
            spadesStops?: null | number | string;
            /** Format: double */
            heartsStops?: null | number | string;
            /** Format: double */
            diamondsStops?: null | number | string;
            /** Format: double */
            clubsStops?: null | number | string;
            colorDistribution?: null | string;
            /** Format: int32 */
            aces?: null | number | string;
            /** Format: int32 */
            kings?: null | number | string;
            openerBid?: boolean;
            signOff?: boolean;
            oneRoundForcing?: boolean;
            gameForcing?: boolean;
            automaticResponse?: boolean;
            goToOpenings?: boolean;
            isPreferred?: boolean;
            isDisabled?: boolean;
            interjection?: null | components["schemas"]["Bid"];
            nextBids?: components["schemas"]["BidNode"][];
            realizedGoal?: components["schemas"]["BiddingGoal"];
            aiSource?: null | string;
            type?: components["schemas"]["BidType"];
            color?: components["schemas"]["BidColor"];
            /** Format: int32 */
            value?: null | number | string;
            isFromSystem?: boolean;
            explanation?: null | string;
        };
        /** @enum {unknown} */
        BidType: "Pass" | "Submit" | "Double" | "Redouble";
        /** @enum {unknown} */
        CardColor: "Clubs" | "Diamonds" | "Hearts" | "Spades";
        /** @enum {unknown} */
        CardValue: "Two" | "Three" | "Four" | "Five" | "Six" | "Seven" | "Eight" | "Nine" | "Ten" | "Jack" | "Queen" | "King" | "Ace";
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        CurrentUser: {
            /** Format: uuid */
            id: string;
            username: string;
            displayName: null | string;
            isAdmin: boolean;
            isDebugBuild: boolean;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        NumberRange: {
            /** Format: int32 */
            lower?: null | number | string;
            /** Format: int32 */
            upper?: null | number | string;
        };
        /** @enum {unknown} */
        PlayerPosition: "North" | "East" | "South" | "West";
        PracticeBidLabel: {
            type: components["schemas"]["BidType"];
            color: components["schemas"]["BidColor"];
            /** Format: int32 */
            value: null | number | string;
            label: string;
        };
        PracticeBidRequest: {
            state: string;
            type: components["schemas"]["BidType"];
            color: components["schemas"]["BidColor"];
            /** Format: int32 */
            value: null | number | string;
        };
        PracticeHint: {
            bid: null | components["schemas"]["PracticeBidLabel"];
            meaning: null | string;
        };
        PracticeHintRequest: {
            state: string;
        };
        PracticeLegalBids: {
            minimumLevel: {
                [key: string]: number | string;
            };
            canDouble: boolean;
            canRedouble: boolean;
        };
        /** @enum {unknown} */
        PracticeRole: "Opener" | "Responder";
        PracticeStartRequest: {
            /** Format: uuid */
            systemId: string;
            /** Format: int32 */
            dealIndex: number | string;
            seed: null | string;
            /** Format: uuid */
            openingNodeId: null | string;
            role: components["schemas"]["PracticeRole"];
            checkBids: boolean;
        };
        PracticeState: {
            state: string;
            /** Format: int32 */
            dealIndex: number | string;
            dealer: components["schemas"]["PlayerPosition"];
            player: components["schemas"]["PlayerPosition"];
            playerHand: components["schemas"]["SimulationHand"];
            bidding: components["schemas"]["SimulationBid"][];
            warnings: components["schemas"]["PracticeWarning"][];
            playerToBid: boolean;
            legal: components["schemas"]["PracticeLegalBids"];
            finished: boolean;
            result: null | components["schemas"]["SimulationDealResult"];
            error: null | string;
        };
        PracticeWarning: {
            /** Format: int32 */
            bidIndex: number | string;
            bid: components["schemas"]["PracticeBidLabel"];
            promised: null | string;
            suggested: null | components["schemas"]["PracticeBidLabel"];
            suggestedMeaning: null | string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        RangeRepair: {
            field: string;
            bound: string;
            /** Format: int32 */
            value: number | string;
        };
        RegisterRequest: {
            username: string;
            password: string;
            displayName: null | string;
        };
        RenameSystemRequest: {
            name: string;
        };
        Root: {
            name?: null | string;
            bids?: components["schemas"]["BidNode"][];
        };
        SaveSystemRequest: {
            name: string;
            system: components["schemas"]["BiddingSystem"];
        };
        SimulationBid: {
            /** Format: int32 */
            index: number | string;
            bidder: components["schemas"]["PlayerPosition"];
            type: components["schemas"]["BidType"];
            color: components["schemas"]["BidColor"];
            /** Format: int32 */
            value: null | number | string;
            isFromSystem: boolean;
            label: string;
            explanation: null | string;
        };
        SimulationCard: {
            value: components["schemas"]["CardValue"];
            color: components["schemas"]["CardColor"];
            label: string;
        };
        SimulationContract: {
            passed: boolean;
            declarer: null | components["schemas"]["PlayerPosition"];
            /** Format: int32 */
            value: null | number | string;
            color: components["schemas"]["BidColor"];
            isDoubled: boolean;
            isRedoubled: boolean;
            label: string;
            /** Format: int32 */
            pairPoints: null | number | string;
            /** Format: int32 */
            trumpCount: null | number | string;
        };
        SimulationDealRequest: {
            dealer: components["schemas"]["PlayerPosition"];
            hands: components["schemas"]["SimulationHandRequest"][];
        };
        SimulationDealResult: {
            /** Format: int32 */
            index: number | string;
            dealer: components["schemas"]["PlayerPosition"];
            hands: components["schemas"]["SimulationHand"][];
            bidding: components["schemas"]["SimulationBid"][];
            contract: components["schemas"]["SimulationContract"];
            error: null | string;
        };
        SimulationHand: {
            position: components["schemas"]["PlayerPosition"];
            cards: components["schemas"]["SimulationCard"][];
            /** Format: int32 */
            points: number | string;
            /** Format: int32 */
            pointsNt: number | string;
            /** Format: int32 */
            spades: number | string;
            /** Format: int32 */
            hearts: number | string;
            /** Format: int32 */
            diamonds: number | string;
            /** Format: int32 */
            clubs: number | string;
        };
        SimulationHandRequest: {
            position: components["schemas"]["PlayerPosition"];
            cards: components["schemas"]["SimulationCard"][];
        };
        SimulationRequest: {
            /** Format: uuid */
            systemId: string;
            deals: components["schemas"]["SimulationDealRequest"][];
            seed?: null | string;
        };
        SimulationResponse: {
            systemName: string;
            /** Format: int32 */
            dealCount: number | string;
            /** Format: int32 */
            failedCount: number | string;
            deals: components["schemas"]["SimulationDealResult"][];
            seed?: null | string;
        };
        UpdateProfileRequest: {
            displayName: null | string;
        };
        ValidationIssue: {
            severity: components["schemas"]["ValidationSeverity"];
            message: string;
            path: string;
            /** Format: uuid */
            nodeId?: null | string;
            conventionContext?: null | string;
            repair?: components["schemas"]["RangeRepair"];
            conditionRepair?: null | string;
        };
        /** @enum {unknown} */
        ValidationSeverity: "Info" | "Warning" | "Error";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
