/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bidding-systems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BiddingSystemSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bidding-systems/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BiddingSystem"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BiddingSystem"];
                    "text/json": components["schemas"]["BiddingSystem"];
                    "application/*+json": components["schemas"]["BiddingSystem"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BiddingSystemSummary"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bidding-systems/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BiddingSystem"];
                    "text/json": components["schemas"]["BiddingSystem"];
                    "application/*+json": components["schemas"]["BiddingSystem"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationIssue"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        BidColor: "NoColor" | "Clubs" | "Diamonds" | "Hearts" | "Spades" | "NoTrump";
        BiddingGoal: number;
        BiddingSystem: {
            systemName?: string;
            roots?: components["schemas"]["Root"][];
        };
        BiddingSystemSummary: {
            name: string;
            /** Format: int32 */
            rootCount: number | string;
            /** Format: int32 */
            bidCount: number | string;
            /** Format: date-time */
            modifiedUtc: string;
        };
        BidNode: {
            description?: null | string;
            condition?: null | string;
            convention?: null | string;
            pointsRange?: null | components["schemas"]["NumberRange"];
            spadesCardRange?: null | components["schemas"]["NumberRange"];
            heartsCardRange?: null | components["schemas"]["NumberRange"];
            diamondsCardRange?: null | components["schemas"]["NumberRange"];
            clubsCardRange?: null | components["schemas"]["NumberRange"];
            /** Format: double */
            spadesStops?: null | number | string;
            /** Format: double */
            heartsStops?: null | number | string;
            /** Format: double */
            diamondsStops?: null | number | string;
            /** Format: double */
            clubsStops?: null | number | string;
            colorDistribution?: null | string;
            /** Format: int32 */
            aces?: null | number | string;
            /** Format: int32 */
            kings?: null | number | string;
            openerBid?: boolean;
            signOff?: boolean;
            oneRoundForcing?: boolean;
            gameForcing?: boolean;
            automaticResponse?: boolean;
            goToOpenings?: boolean;
            nextBids?: components["schemas"]["BidNode"][];
            realizedGoal?: components["schemas"]["BiddingGoal"];
            aiSource?: null | string;
            type?: components["schemas"]["BidType"];
            color?: components["schemas"]["BidColor"];
            /** Format: int32 */
            value?: null | number | string;
            isFromSystem?: boolean;
        };
        /** @enum {unknown} */
        BidType: "Pass" | "Submit" | "Double" | "Redouble";
        NumberRange: {
            /** Format: int32 */
            lower?: null | number | string;
            /** Format: int32 */
            upper?: null | number | string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        Root: {
            name?: null | string;
            bids?: components["schemas"]["BidNode"][];
        };
        ValidationIssue: {
            severity: components["schemas"]["ValidationSeverity"];
            message: string;
            path: string;
            conventionContext?: null | string;
        };
        /** @enum {unknown} */
        ValidationSeverity: "Info" | "Warning" | "Error";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
